
package ec.edu.monster.ws.conuni;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WSEureka", targetNamespace = "http://ws.monster.edu.ec/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSEureka {


    /**
     * 
     * @param cuenta
     * @return
     *     returns java.util.List<ec.edu.monster.ws.conuni.Movimiento>
     */
    @WebMethod
    @WebResult(name = "movimiento", targetNamespace = "")
    @RequestWrapper(localName = "traerMovimientos", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.conuni.TraerMovimientos")
    @ResponseWrapper(localName = "traerMovimientosResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.conuni.TraerMovimientosResponse")
    @Action(input = "http://ws.monster.edu.ec/WSEureka/traerMovimientosRequest", output = "http://ws.monster.edu.ec/WSEureka/traerMovimientosResponse")
    public List<Movimiento> traerMovimientos(
        @WebParam(name = "cuenta", targetNamespace = "")
        String cuenta);

    /**
     * 
     * @param cuenta
     * @param importe
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "regDeposito", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.conuni.RegDeposito")
    @ResponseWrapper(localName = "regDepositoResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.conuni.RegDepositoResponse")
    @Action(input = "http://ws.monster.edu.ec/WSEureka/regDepositoRequest", output = "http://ws.monster.edu.ec/WSEureka/regDepositoResponse")
    public int regDeposito(
        @WebParam(name = "cuenta", targetNamespace = "")
        String cuenta,
        @WebParam(name = "importe", targetNamespace = "")
        double importe);

    /**
     * 
     * @param usuario
     * @param contrasena
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "login", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.conuni.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.conuni.LoginResponse")
    @Action(input = "http://ws.monster.edu.ec/WSEureka/loginRequest", output = "http://ws.monster.edu.ec/WSEureka/loginResponse")
    public int login(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasena", targetNamespace = "")
        String contrasena);

    /**
     * 
     * @param cuenta
     * @param importe
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "regRetiro", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.conuni.RegRetiro")
    @ResponseWrapper(localName = "regRetiroResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.conuni.RegRetiroResponse")
    @Action(input = "http://ws.monster.edu.ec/WSEureka/regRetiroRequest", output = "http://ws.monster.edu.ec/WSEureka/regRetiroResponse")
    public int regRetiro(
        @WebParam(name = "cuenta", targetNamespace = "")
        String cuenta,
        @WebParam(name = "importe", targetNamespace = "")
        double importe);

    /**
     * 
     * @param cuentaDestino
     * @param cuentaOrigen
     * @param importe
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "regTransferencia", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.conuni.RegTransferencia")
    @ResponseWrapper(localName = "regTransferenciaResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.conuni.RegTransferenciaResponse")
    @Action(input = "http://ws.monster.edu.ec/WSEureka/regTransferenciaRequest", output = "http://ws.monster.edu.ec/WSEureka/regTransferenciaResponse")
    public int regTransferencia(
        @WebParam(name = "cuentaOrigen", targetNamespace = "")
        String cuentaOrigen,
        @WebParam(name = "cuentaDestino", targetNamespace = "")
        String cuentaDestino,
        @WebParam(name = "importe", targetNamespace = "")
        double importe);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "cuenta", targetNamespace = "")
    @RequestWrapper(localName = "traerCuentas", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.conuni.TraerCuentas")
    @ResponseWrapper(localName = "traerCuentasResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.conuni.TraerCuentasResponse")
    @Action(input = "http://ws.monster.edu.ec/WSEureka/traerCuentasRequest", output = "http://ws.monster.edu.ec/WSEureka/traerCuentasResponse")
    public List<String> traerCuentas();

    /**
     * 
     * @param cuenta
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "monto", targetNamespace = "")
    @RequestWrapper(localName = "traerMonto", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.conuni.TraerMonto")
    @ResponseWrapper(localName = "traerMontoResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.conuni.TraerMontoResponse")
    @Action(input = "http://ws.monster.edu.ec/WSEureka/traerMontoRequest", output = "http://ws.monster.edu.ec/WSEureka/traerMontoResponse")
    public double traerMonto(
        @WebParam(name = "cuenta", targetNamespace = "")
        String cuenta);

    /**
     * 
     * @return
     *     returns java.util.List<ec.edu.monster.ws.conuni.Empleado>
     */
    @WebMethod
    @WebResult(name = "empleado", targetNamespace = "")
    @RequestWrapper(localName = "traerEmpleados", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.conuni.TraerEmpleados")
    @ResponseWrapper(localName = "traerEmpleadosResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.conuni.TraerEmpleadosResponse")
    @Action(input = "http://ws.monster.edu.ec/WSEureka/traerEmpleadosRequest", output = "http://ws.monster.edu.ec/WSEureka/traerEmpleadosResponse")
    public List<Empleado> traerEmpleados();

    /**
     * 
     * @param materno
     * @param codigo
     * @param paterno
     * @param ciudad
     * @param direccion
     * @param nombre
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "crearEmpleado", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.conuni.CrearEmpleado")
    @ResponseWrapper(localName = "crearEmpleadoResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.conuni.CrearEmpleadoResponse")
    @Action(input = "http://ws.monster.edu.ec/WSEureka/crearEmpleadoRequest", output = "http://ws.monster.edu.ec/WSEureka/crearEmpleadoResponse")
    public int crearEmpleado(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo,
        @WebParam(name = "paterno", targetNamespace = "")
        String paterno,
        @WebParam(name = "materno", targetNamespace = "")
        String materno,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "ciudad", targetNamespace = "")
        String ciudad,
        @WebParam(name = "direccion", targetNamespace = "")
        String direccion);

}
